[project]
name = "predict-iidx-diff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lightgbm>=4.6.0",
    "lxml>=6.0.2",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "playwright>=1.58.0",
    "pyjsparser>=2.7.1",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
]
